# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', 'm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='fecha_recogida',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='foto',
            field=models.ImageField(default='', upload_to='prueba'),
            preserve_default=False,
        ),
    ]
