# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_auto_20170314_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
